### ISSUE TITLE
V grafu podle pojištění chybí data s hodnotou "Ano"

### ISSUE THREAD

**Issue by liry** [RoboZonky/zonky-loanbook#3]
V grafu "Zesplatněné půjčky podle pojištění, od jeho zavedení" chybí data s hodnotou "Ano" (Má pojištění). Pro hodnotu "Ne" data jsou.

**Comment by triceo** [comment]
Hm, zajímavé. To bude nějaká zrada ve vstupních datech. Díky za report!

**Comment by triceo** [comment]
Tak jsem to prozkoumal a nejde o chybu na mojí straně. Ten graf reflektuje přesně to, co je v loanbooku - a loanbook říká, že z ukončených půjček žádná nebyla pojištěná.

To je nejspíš nesmysl. Nebo pokud není, tak byly nesmysly v předchozích verzích loanbooku, kde v téhle kategorii byla úplně jiná čísla. Tak jako tak s tím budu Zonky konfrontovat.

**Comment by triceo** [comment]
Tak ta data nejsou a nejspíš už nikdy nebudou. Takže nová verze stránek za květen je už bez tohohle grafu.
Díky za upozornění!
